"""add_graph_security_obs_notification

Revision ID: 00fe9d0489d1
Revises: d8fe5039a9d1
Create Date: 2026-08-18 17:17:07.751383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00fe9d0489d1'
down_revision: Union[str, Sequence[str], None] = 'd8fe5039a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_node',
    sa.Column('graph_key', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=256), nullable=True),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_graph_node_external_ref', 'graph_node', ['graph_key', 'node_type', 'external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.create_table('obs_llm_call',
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obs_span',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('span_id')
    )
    op.create_table('obs_tool_invocation',
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('tool_code', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obs_trace',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_table('sec_guardrail_rule',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('graph_edge',
    sa.Column('graph_key', sa.String(length=64), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_node.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_edge_source', 'graph_edge', ['source_node_id'], unique=False)
    op.create_index('idx_graph_edge_target', 'graph_edge', ['target_node_id'], unique=False)
    op.create_table('graph_entity_link',
    sa.Column('entity_name', sa.String(length=256), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['graph_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_name', 'node_id', name='uq_entity_node')
    )
    op.create_table('notify_webhook_endpoint',
    sa.Column('owner_organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['sys_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obs_prompt_snapshot',
    sa.Column('llm_call_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content_redacted', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['obs_llm_call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_policy_violation',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('matched_excerpt', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['sec_guardrail_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notify_delivery_log',
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['notify_webhook_endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notify_delivery_log')
    op.drop_table('sec_policy_violation')
    op.drop_table('obs_prompt_snapshot')
    op.drop_table('notify_webhook_endpoint')
    op.drop_table('graph_entity_link')
    op.drop_index('idx_graph_edge_target', table_name='graph_edge')
    op.drop_index('idx_graph_edge_source', table_name='graph_edge')
    op.drop_table('graph_edge')
    op.drop_table('sec_guardrail_rule')
    op.drop_table('obs_trace')
    op.drop_table('obs_tool_invocation')
    op.drop_table('obs_span')
    op.drop_table('obs_llm_call')
    op.drop_index('uq_graph_node_external_ref', table_name='graph_node', postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.drop_table('graph_node')
    # ### end Alembic commands ###
